### ISSUE TITLE
默认时区不是中国，与北京时间不一致

### ISSUE THREAD

**Issue by geekyouth** [xiyangxixian/soar-web#102]
![image](https://user-images.githubusercontent.com/12899262/77250207-460c1780-6c81-11ea-92ce-b5cfe0a81ba1.png)

## 和北京时间相差8小时，应该是默认使用零时区的时间了，建议默认配置采用北京时间。毕竟是国人开源作品。

**Comment by xbw1220** [comment]
自己配个时区都不会的嘛。。。
