### ISSUE TITLE
explain信息如何配置

### ISSUE THREAD

**Issue by wfeang** [xiyangxixian/soar-web#106]
在启动项目之后，直接访问没有显示explain的配置信息。我试图配置config.py中的explain-format: traditional，但提示traditional不存在，请问应当如何配置有相关的配置案例吗？

**Comment by xiyangxixian** [comment]
需要保证数据库连接正确，然后权限正确，确定测试连接和线上连接是不是一致的情况，不一致的话，无影响，一致的情况下，需要将允许线上连接作为测试连接勾选上。
