### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by wangbincode** [xiyangxixian/soar-web#22]

**Comment by wangbincode** [comment]
windows下，命令行评估不报错，使用ui界面评估就报错；测试评估代码如下：
SELECT a.table_name 表名, a.table_comment 表说明, b.COLUMN_NAME 字段名, b.column_comment 字段说明, b.column_type 字段类型, b.column_key 约束 FROM information_schema. TABLES a LEFT JOIN information_schema. COLUMNS b ON a.table_name = b.TABLE_NAME WHERE a.table_schema IN ('a')  AND b.column_comment LIKE '%一%'  ORDER BY a.table_name

**Comment by wangbincode** [comment]
windows下，命令行评估不报错，使用ui界面评估就报错；测试评估代码如下：
SELECT a.table_name 表名, a.table_comment 表说明, b.COLUMN_NAME 字段名, b.column_comment 字段说明, b.column_type 字段类型, b.column_key 约束 FROM information_schema. TABLES a LEFT JOIN information_schema. COLUMNS b ON a.table_name = b.TABLE_NAME WHERE a.table_schema IN ('a') AND b.column_comment LIKE '%一%' ORDER BY a.table_name

**Comment by xiyangxixian** [comment]
@wangbincode 已经找到原因了, 是中文造成的问题, 之后我们会修复这个问题, 谢谢反馈

**Comment by xiyangxixian** [comment]
编码问题已经修复 @wangbincode
