### ISSUE TITLE
配置里没有端口号设置，不是默认的3306端口

### ISSUE THREAD

**Issue by k9990009** [xiyangxixian/soar-web#4]
RT

**Comment by xiyangxixian** [comment]
@k9990009 
截图中给的例子不全, 可在在主机后加端口号。
完整的dsn例子是 user:password@host:port/db

**Comment by k9990009** [comment]
我一直连不上，又看到test-connect里没有对port解析，还以为有问题

**Comment by xiyangxixian** [comment]
@k9990009 这个问题刚刚修复了, 谢谢反馈
