### ISSUE TITLE
没有安装成功

### ISSUE THREAD

**Issue by hdpter** [xiyangxixian/soar-web#6]
您好，没有安装成功，错误提示如下：
`Traceback (most recent call last):
  File "./soar-web.py", line 22, in <module>
    from core.common import soar_result
  File "/home/xxx/project/soar-web/core/common.py", line 16, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse`

我系统环境为 centos
sudo yum install python34 python34-pip

**Comment by xiyangxixian** [comment]
@hdpter 
run.sh 里面用的是默认的python版本, 如果系统中存在多个版本的python, 在run.sh 里面的python改为指定版本执行。
比如在你的例子中, 在将 run.sh 中 
python $dir/soar-web.py
改为
python34 $dir/soar-web.py
之后我会对 2.x 的版本做一些兼容的处理, 谢谢反馈。

**Comment by Becivells** [comment]
@hdpter python2.7 已经支持
