### ISSUE TITLE
语法正确的语句美化后再做语法检查就报错

### ISSUE THREAD

**Issue by smooth00** [xiyangxixian/soar-web#78]
语法正确的语句，如下：
![image](https://user-images.githubusercontent.com/43713947/49354135-42572900-f6fc-11e8-9013-2a4f14cf7ce5.png)
点击美化后，再对美化后的语句检查就报错：
![image](https://user-images.githubusercontent.com/43713947/49354207-8fd39600-f6fc-11e8-916b-c9ed1731a47b.png)
应该是和语句的长度或复杂度有关

**Comment by smooth00** [comment]
补充：使用的是最新版的源码，或是2018年11月30日发布的docker都能出现这种问题。

**Comment by xiyangxixian** [comment]
@smooth00 方便在 issue 里面贴一下sql吗, 谢谢

**Comment by smooth00** [comment]
SELECT name, GROUP_CONCAT(realname) as realname1, sum(gs) as gs
FROM (
SELECT p1.name, p1.`code`, u.realname, s.ssgs 
    , SUM( zt.consumed ) AS 'gs',date_format(now(), '%Y-%m') as yf,((DAY(now())+WEEKDAY(now()-INTERVAL DAY(now()) DAY)) DIV 7) as jz
FROM zt_taskestimate zt 
    INNER JOIN zt_task t ON t.id = zt.task 
    LEFT JOIN zt_project p ON p.id = t.project 
    LEFT JOIN zt_user u ON u.account = zt.account 
    LEFT JOIN zt_skunk s ON u.realname = s.name 
    LEFT JOIN zt_projectproduct p2 ON p.id = p2.project 
    LEFT JOIN zt_product p1 ON p2.product = p1.id 
WHERE date>=DATE_SUB(now(), INTERVAL 7 DAY)
GROUP BY p1.name, u.realname, u.account
) cb_view 

GROUP BY code,  name ORDER BY gs desc

**Comment by xiyangxixian** [comment]
soar 中, 在处理 date 的时候存在关键字冲突, 待修复

**Comment by xiyangxixian** [comment]
已经修复
