### ISSUE TITLE
数据库连接验证格式的问题

### ISSUE THREAD

**Issue by Hather-Clare** [xiyangxixian/soar-web#94]
线上数据库密码带"@"符号，测试连接数据库会把密码字符"@"的后半段识别成主机地址

**Comment by Becivells** [comment]
特殊符号可以使用\@

**Comment by Becivells** [comment]
这个问题我们已经解决了。应该是代码还没提交。可以暂时使用\@ 的形式进程转义

**Comment by Becivells** [comment]
反斜杠@

**Comment by Hather-Clare** [comment]
我用的是docker镜像，用""\@"貌似没用，"_"和"#"应该都不需要转义的吧？

**Comment by Becivells** [comment]
能把密码的格式发一下么。随便写点字符串我这边复现不了

**Comment by Hather-Clare** [comment]
admin_root@bj#1213

**Comment by Becivells** [comment]
好的我试下，也可以加到我们群里面。沟通比较方便

**Comment by Hather-Clare** [comment]
好

**Comment by Becivells** [comment]
你重新拉一下 docker (docker pull becivells/soar-web)。重新启动一个容器。就没问题了，新版本的没来得及更新上。

**Comment by Hather-Clare** [comment]
我明天更新下，电脑不在身边，谢谢啦

**Comment by Becivells** [comment]
好的刚刚我试了没问题。如果有问题再联系
